services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app

  redis:
    ports: ["6379"]

  worker:

  db:
    image: postgres:9.4

  result:
    build: ./result
    command: nodemon server.js
    ports:
      - "5001:80"
      - "5858:5858"
